// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";
import { DATABASE_URL } from "../backend/src/config/envConfig";

const url = process.env.DB_URL || DATABASE_URL;
if (!url) {
  throw new Error(
    "Database URL not set. Please set DB_URL or DATABASE_URL in your environment or .env before running Prisma commands.",
  );
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url,
  },
});

console.log(url);
